/**
 * Worker Seed Script
 * Creates 20 worker accounts with full profiles for Offerly.
 *
 * Usage:  node scripts/seedWorkers.js
 */

const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
require("dotenv").config();

const User = require("../models/User");
const WorkerProfile = require("../models/WorkerProfile");

const workers = [
    {
        name: "Kumar R",
        email: "kumar01@gmail.com",
        password: "Kumar@123",
        mobile: "8248750293",
        experience: 2,
        salary: 700,
        location: "Sathyamangalam, Erode",
        jobCategory: "Electrician",
        skills: ["Electrician"],
        subSkills: ["Wiring", "Switch Installation"]
    },
    {
        name: "Moorthy K",
        email: "moorthy02@gmail.com",
        password: "Moorthy@123",
        mobile: "8248750294",
        experience: 1,
        salary: 600,
        location: "Puliyampatti, Erode",
        jobCategory: "Electrician",
        skills: ["Electrician"],
        subSkills: ["Fan Installation", "Light Repair"]
    },
    {
        name: "Sobana M",
        email: "sobana03@gmail.com",
        password: "Sobana@123",
        mobile: "9965143321",
        experience: 5,
        salary: 800,
        location: "Puliyampatti, Erode",
        jobCategory: "Electrician",
        skills: ["Electrician"],
        subSkills: ["House Wiring", "Inverter Setup"]
    },
    {
        name: "Ramesh S",
        email: "ramesh04@gmail.com",
        password: "Ramesh@123",
        mobile: "9845632109",
        experience: 3,
        salary: 750,
        location: "Coimbatore",
        jobCategory: "Plumber",
        skills: ["Plumber"],
        subSkills: ["Pipe Fitting", "Water Tank Installation"]
    },
    {
        name: "Suresh K",
        email: "suresh05@gmail.com",
        password: "Suresh@123",
        mobile: "9785641230",
        experience: 4,
        salary: 900,
        location: "Tiruppur",
        jobCategory: "Carpenter",
        skills: ["Carpenter"],
        subSkills: ["Furniture Repair", "Door Installation"]
    },
    {
        name: "Mani P",
        email: "mani06@gmail.com",
        password: "Mani@123",
        mobile: "9345612789",
        experience: 2,
        salary: 650,
        location: "Salem",
        jobCategory: "Painter",
        skills: ["Painter"],
        subSkills: ["Wall Painting", "Putty Work"]
    },
    {
        name: "Gopi M",
        email: "gopi07@gmail.com",
        password: "Gopi@123",
        mobile: "9564781234",
        experience: 5,
        salary: 1000,
        location: "Erode",
        jobCategory: "AC Technician",
        skills: ["AC Technician"],
        subSkills: ["AC Installation", "Gas Refilling"]
    },
    {
        name: "Selvam R",
        email: "selvam08@gmail.com",
        password: "Selvam@123",
        mobile: "9896543210",
        experience: 6,
        salary: 950,
        location: "Namakkal",
        jobCategory: "Welder",
        skills: ["Welder"],
        subSkills: ["Iron Welding", "Gate Fabrication"]
    },
    {
        name: "Prakash V",
        email: "prakash09@gmail.com",
        password: "Prakash@123",
        mobile: "9123456789",
        experience: 7,
        salary: 850,
        location: "Karur",
        jobCategory: "Mason",
        skills: ["Mason"],
        subSkills: ["Brick Work", "Cement Finishing"]
    },
    {
        name: "Arun T",
        email: "arun10@gmail.com",
        password: "Arun@123",
        mobile: "9784512367",
        experience: 2,
        salary: 500,
        location: "Madurai",
        jobCategory: "House Cleaner",
        skills: ["House Cleaner"],
        subSkills: ["Deep Cleaning", "Floor Polishing"]
    },
    {
        name: "Dinesh K",
        email: "dinesh11@gmail.com",
        password: "Dinesh@123",
        mobile: "9874512365",
        experience: 4,
        salary: 800,
        location: "Erode",
        jobCategory: "Driver",
        skills: ["Driver"],
        subSkills: ["Local Driving", "Delivery Service"]
    },
    {
        name: "Ravi P",
        email: "ravi12@gmail.com",
        password: "Ravi@123",
        mobile: "9564781256",
        experience: 3,
        salary: 900,
        location: "Coimbatore",
        jobCategory: "Refrigerator Technician",
        skills: ["Refrigerator Technician"],
        subSkills: ["Gas Refilling", "Compressor Repair"]
    },
    {
        name: "Murugan S",
        email: "murugan13@gmail.com",
        password: "Murugan@123",
        mobile: "9345678912",
        experience: 6,
        salary: 950,
        location: "Salem",
        jobCategory: "Tile Worker",
        skills: ["Tile Worker"],
        subSkills: ["Floor Tiles", "Wall Tiles"]
    },
    {
        name: "Karthik R",
        email: "karthik14@gmail.com",
        password: "Karthik@123",
        mobile: "9786541230",
        experience: 3,
        salary: 850,
        location: "Tiruppur",
        jobCategory: "CCTV Installer",
        skills: ["CCTV Installer"],
        subSkills: ["Camera Setup", "Security Systems"]
    },
    {
        name: "Senthil M",
        email: "senthil15@gmail.com",
        password: "Senthil@123",
        mobile: "9894512367",
        experience: 8,
        salary: 1200,
        location: "Namakkal",
        jobCategory: "Borewell Mechanic",
        skills: ["Borewell Mechanic"],
        subSkills: ["Pump Repair", "Motor Installation"]
    },
    {
        name: "Bala T",
        email: "bala16@gmail.com",
        password: "Bala@123",
        mobile: "9123487654",
        experience: 2,
        salary: 600,
        location: "Karur",
        jobCategory: "Gardening Worker",
        skills: ["Gardening Worker"],
        subSkills: ["Lawn Cutting", "Plant Care"]
    },
    {
        name: "Vignesh P",
        email: "vignesh17@gmail.com",
        password: "Vignesh@123",
        mobile: "9345612345",
        experience: 3,
        salary: 700,
        location: "Erode",
        jobCategory: "Water Tank Cleaner",
        skills: ["Water Tank Cleaner"],
        subSkills: ["Tank Washing", "Pipe Cleaning"]
    },
    {
        name: "Rajesh K",
        email: "rajesh18@gmail.com",
        password: "Rajesh@123",
        mobile: "9564789123",
        experience: 4,
        salary: 900,
        location: "Coimbatore",
        jobCategory: "Laptop Repair",
        skills: ["Laptop Repair"],
        subSkills: ["Hardware Repair", "Software Installation"]
    },
    {
        name: "Naveen S",
        email: "naveen19@gmail.com",
        password: "Naveen@123",
        mobile: "9876541230",
        experience: 5,
        salary: 850,
        location: "Tiruppur",
        jobCategory: "Mobile Repair",
        skills: ["Mobile Repair"],
        subSkills: ["Screen Replacement", "Battery Repair"]
    },
    {
        name: "Hari M",
        email: "hari20@gmail.com",
        password: "Hari@123",
        mobile: "9785647890",
        experience: 3,
        salary: 750,
        location: "Salem",
        jobCategory: "Pest Control Worker",
        skills: ["Pest Control Worker"],
        subSkills: ["Termite Control", "Mosquito Treatment"]
    },
    { name: "Murugan", email: "murugan11@gmail.com", password: "Murugan@123", mobile: "8752360011", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Cutting"] },
    { name: "Gopi", email: "gopi12@gmail.com", password: "Gopi@123", mobile: "8752360012", experience: 4, salary: 800, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Color Mixing"] },
    { name: "Bala", email: "bala13@gmail.com", password: "Bala@123", mobile: "8752360013", experience: 6, salary: 950, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Switchboard Install"] },
    { name: "Ravi Kumar", email: "ravi14@gmail.com", password: "Ravi@123", mobile: "8752360014", experience: 7, salary: 1000, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Selvam", email: "selvam15@gmail.com", password: "Selvam@123", mobile: "8752360015", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Anand", email: "anand16@gmail.com", password: "Anand@123", mobile: "8752360016", experience: 6, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Mahesh", email: "mahesh17@gmail.com", password: "Mahesh@123", mobile: "8752360017", experience: 5, salary: 950, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Install", "Gas Refilling"] },
    { name: "Pandian", email: "pandian18@gmail.com", password: "Pandian@123", mobile: "8752360018", experience: 7, salary: 1000, location: "Namakkal", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Motor Wiring", "Panel Board"] },
    { name: "Raghu", email: "raghu19@gmail.com", password: "Raghu@123", mobile: "8752360019", experience: 6, salary: 900, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipeline Work", "Bathroom Repair"] },
    { name: "Sekar", email: "sekar20@gmail.com", password: "Sekar@123", mobile: "8752360020", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Cutting"] },
    { name: "Arun Kumar", email: "arun1@gmail.com", password: "Arun@123", mobile: "8752360001", experience: 5, salary: 900, location: "Erode", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Switchboard Install"] },
    { name: "Karthik Raj", email: "karthik2@gmail.com", password: "Karthik@123", mobile: "8752360002", experience: 4, salary: 850, location: "Coimbatore", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Senthil Kumar", email: "senthil3@gmail.com", password: "Senthil@123", mobile: "8752360003", experience: 6, salary: 950, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Polishing"] },
    { name: "Prakash Raj", email: "prakash4@gmail.com", password: "Prakash@123", mobile: "8752360004", experience: 7, salary: 800, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Texture Painting"] },
    { name: "Vignesh Kumar", email: "vignesh5@gmail.com", password: "Vignesh@123", mobile: "8752360005", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Manikandan", email: "manikandan6@gmail.com", password: "Manikandan@123", mobile: "8752360006", experience: 5, salary: 900, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Suresh Kumar", email: "suresh7@gmail.com", password: "Suresh@123", mobile: "8752360007", experience: 6, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Dinesh Kumar", email: "dinesh8@gmail.com", password: "Dinesh@123", mobile: "8752360008", experience: 4, salary: 950, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Install", "Gas Refilling"] },
    { name: "Saravanan", email: "saravanan9@gmail.com", password: "Saravanan@123", mobile: "8752360009", experience: 7, salary: 1000, location: "Namakkal", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Motor Wiring", "Panel Board"] },
    { name: "Ramesh Kumar", email: "ramesh10@gmail.com", password: "Ramesh@123", mobile: "8752360010", experience: 6, salary: 900, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipeline Work", "Bathroom Repair"] },
    { name: "Yogesh", email: "yogesh21@gmail.com", password: "Yogesh@123", mobile: "8752360021", experience: 5, salary: 850, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Color Mixing"] },
    { name: "Ajith", email: "ajith22@gmail.com", password: "Ajith@123", mobile: "8752360022", experience: 6, salary: 950, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Motor Wiring"] },
    { name: "Balaji", email: "balaji23@gmail.com", password: "Balaji@123", mobile: "8752360023", experience: 7, salary: 1000, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Deva", email: "deva24@gmail.com", password: "Deva@123", mobile: "8752360024", experience: 5, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Raja", email: "raja25@gmail.com", password: "Raja@123", mobile: "8752360025", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Sathish", email: "sathish26@gmail.com", password: "Sathish@123", mobile: "8752360026", experience: 4, salary: 900, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Install", "Gas Refilling"] },
    { name: "Kannan", email: "kannan27@gmail.com", password: "Kannan@123", mobile: "8752360027", experience: 6, salary: 950, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Polishing"] },
    { name: "Muthu", email: "muthu28@gmail.com", password: "Muthu@123", mobile: "8752360028", experience: 7, salary: 1000, location: "Namakkal", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Panel Board", "Motor Wiring"] },
    { name: "Perumal", email: "perumal29@gmail.com", password: "Perumal@123", mobile: "8752360029", experience: 6, salary: 900, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipeline Work", "Bathroom Repair"] },
    { name: "Logesh", email: "logesh30@gmail.com", password: "Logesh@123", mobile: "8752360030", experience: 5, salary: 850, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Texture Painting"] },
    { name: "Chandru", email: "chandru31@gmail.com", password: "Chandru@123", mobile: "8752360031", experience: 6, salary: 950, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Ilango", email: "ilango32@gmail.com", password: "Ilango@123", mobile: "8752360032", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Jagan", email: "jagan33@gmail.com", password: "Jagan@123", mobile: "8752360033", experience: 5, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Lakshman", email: "lakshman34@gmail.com", password: "Lakshman@123", mobile: "8752360034", experience: 7, salary: 1000, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Motor Wiring", "Switchboard Install"] },
    { name: "Naren", email: "naren35@gmail.com", password: "Naren@123", mobile: "8752360035", experience: 4, salary: 900, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Install", "Gas Refilling"] },
    { name: "Pandian", email: "pandian36@gmail.com", password: "Pandian@123", mobile: "8752360036", experience: 6, salary: 950, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Cutting"] },
    { name: "Raghu", email: "raghu37@gmail.com", password: "Raghu@123", mobile: "8752360037", experience: 5, salary: 850, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Color Mixing"] },
    { name: "Sekar", email: "sekar38@gmail.com", password: "Sekar@123", mobile: "8752360038", experience: 6, salary: 900, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipeline Work", "Bathroom Repair"] },
    { name: "Thangavel", email: "thangavel39@gmail.com", password: "Thangavel@123", mobile: "8752360039", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Uday", email: "uday40@gmail.com", password: "Uday@123", mobile: "8752360040", experience: 5, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Varun", email: "varun41@gmail.com", password: "Varun@123", mobile: "8752360041", experience: 6, salary: 950, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Motor Wiring", "Switchboard Install"] },
    { name: "Yogesh", email: "yogesh42@gmail.com", password: "Yogesh@123", mobile: "8752360042", experience: 7, salary: 1000, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Ajith Kumar", email: "ajith43@gmail.com", password: "Ajith@123", mobile: "8752360043", experience: 6, salary: 950, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Work", "Wood Polishing"] },
    { name: "Balaji", email: "balaji44@gmail.com", password: "Balaji@123", mobile: "8752360044", experience: 5, salary: 850, location: "Madurai", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Putty", "Texture Painting"] },
    { name: "Chandran", email: "chandran45@gmail.com", password: "Chandran@123", mobile: "8752360045", experience: 6, salary: 900, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipeline Work", "Bathroom Repair"] },
    { name: "Devaraj", email: "devaraj46@gmail.com", password: "Devaraj@123", mobile: "8752360046", experience: 8, salary: 950, location: "Trichy", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Elango", email: "elango47@gmail.com", password: "Elango@123", mobile: "8752360047", experience: 5, salary: 850, location: "Chennai", jobCategory: "Driver", skills: ["Driver"], subSkills: ["Car Driving", "Van Driving"] },
    { name: "Ganesan", email: "ganesan48@gmail.com", password: "Ganesan@123", mobile: "8752360048", experience: 7, salary: 1000, location: "Namakkal", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Motor Wiring", "Panel Board"] },
    { name: "Hari", email: "hari49@gmail.com", password: "Hari@123", mobile: "8752360049", experience: 4, salary: 900, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Install", "Gas Refilling"] },
    { name: "Jeeva", email: "jeeva50@gmail.com", password: "Jeeva@123", mobile: "8752360050", experience: 6, salary: 950, location: "Hosur", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Rajesh", email: "rajesh1@gmail.com", password: "Rajesh@123", mobile: "8752360001", experience: 10, salary: 1100, location: "Dharmapuri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Inverter Setup"] },
    { name: "Kumar", email: "kumar2@gmail.com", password: "Kumar@123", mobile: "8752360002", experience: 8, salary: 900, location: "Salem", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Suresh", email: "suresh3@gmail.com", password: "Suresh@123", mobile: "8752360003", experience: 12, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Ramesh", email: "ramesh4@gmail.com", password: "Ramesh@123", mobile: "8752360004", experience: 7, salary: 850, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Vijay", email: "vijay5@gmail.com", password: "Vijay@123", mobile: "8752360005", experience: 15, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Arun", email: "arun6@gmail.com", password: "Arun@123", mobile: "8752360006", experience: 6, salary: 900, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "House Wiring"] },
    { name: "Prakash", email: "prakash7@gmail.com", password: "Prakash@123", mobile: "8752360007", experience: 11, salary: 1150, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Manoj", email: "manoj8@gmail.com", password: "Manoj@123", mobile: "8752360008", experience: 9, salary: 1100, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Karthik", email: "karthik9@gmail.com", password: "Karthik@123", mobile: "8752360009", experience: 10, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Dinesh", email: "dinesh10@gmail.com", password: "Dinesh@123", mobile: "8752360010", experience: 5, salary: 750, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Saravanan", email: "saravanan21@gmail.com", password: "Saravanan@123", mobile: "8752360021", experience: 9, salary: 1050, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Fan Installation"] },
    { name: "Gopi", email: "gopi22@gmail.com", password: "Gopi@123", mobile: "8752360022", experience: 7, salary: 850, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Murugan", email: "murugan23@gmail.com", password: "Murugan@123", mobile: "8752360023", experience: 13, salary: 1250, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Door Installation"] },
    { name: "Bala", email: "bala24@gmail.com", password: "Bala@123", mobile: "8752360024", experience: 6, salary: 800, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Texture Painting"] },
    { name: "Hari", email: "hari25@gmail.com", password: "Hari@123", mobile: "8752360025", experience: 14, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Kumar", email: "kumar26@gmail.com", password: "Kumar@123", mobile: "8752360026", experience: 5, salary: 850, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "Switch Board Repair"] },
    { name: "Prakash", email: "prakash27@gmail.com", password: "Prakash@123", mobile: "8752360027", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Gate Welding"] },
    { name: "Manoj", email: "manoj28@gmail.com", password: "Manoj@123", mobile: "8752360028", experience: 8, salary: 1050, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Karthik", email: "karthik29@gmail.com", password: "Karthik@123", mobile: "8752360029", experience: 9, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Dinesh", email: "dinesh30@gmail.com", password: "Dinesh@123", mobile: "8752360030", experience: 6, salary: 800, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Ravi", email: "ravi31@gmail.com", password: "Ravi@123", mobile: "8752360031", experience: 8, salary: 950, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Switch Board Repair"] },
    { name: "Senthil", email: "senthil32@gmail.com", password: "Senthil@123", mobile: "8752360032", experience: 7, salary: 850, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Venkatesh", email: "venkatesh33@gmail.com", password: "Venkatesh@123", mobile: "8752360033", experience: 11, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Sathish", email: "sathish34@gmail.com", password: "Sathish@123", mobile: "8752360034", experience: 6, salary: 800, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Mani", email: "mani35@gmail.com", password: "Mani@123", mobile: "8752360035", experience: 14, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Ajith", email: "ajith36@gmail.com", password: "Ajith@123", mobile: "8752360036", experience: 5, salary: 850, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "House Wiring"] },
    { name: "Deepak", email: "deepak37@gmail.com", password: "Deepak@123", mobile: "8752360037", experience: 9, salary: 1050, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Gate Welding"] },
    { name: "Naveen", email: "naveen38@gmail.com", password: "Naveen@123", mobile: "8752360038", experience: 8, salary: 1100, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Vinoth", email: "vinoth39@gmail.com", password: "Vinoth@123", mobile: "8752360039", experience: 10, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Praveen", email: "praveen40@gmail.com", password: "Praveen@123", mobile: "8752360040", experience: 6, salary: 820, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Aravind", email: "aravind41@gmail.com", password: "Aravind@123", mobile: "8752360041", experience: 9, salary: 1000, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Fan Installation"] },
    { name: "Baskar", email: "baskar42@gmail.com", password: "Baskar@123", mobile: "8752360042", experience: 7, salary: 850, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Chandran", email: "chandran43@gmail.com", password: "Chandran@123", mobile: "8752360043", experience: 12, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Door Installation"] },
    { name: "Deva", email: "deva44@gmail.com", password: "Deva@123", mobile: "8752360044", experience: 6, salary: 800, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Elango", email: "elango45@gmail.com", password: "Elango@123", mobile: "8752360045", experience: 15, salary: 1350, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Faisal", email: "faisal46@gmail.com", password: "Faisal@123", mobile: "8752360046", experience: 5, salary: 850, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Switch Board Repair", "Fan Installation"] },
    { name: "Ganesh", email: "ganesh47@gmail.com", password: "Ganesh@123", mobile: "8752360047", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Harish", email: "harish48@gmail.com", password: "Harish@123", mobile: "8752360048", experience: 8, salary: 1050, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Ilayaraja", email: "ilayaraja49@gmail.com", password: "Ilayaraja@123", mobile: "8752360049", experience: 9, salary: 980, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Jagan", email: "jagan50@gmail.com", password: "Jagan@123", mobile: "8752360050", experience: 6, salary: 800, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Kannan", email: "kannan51@gmail.com", password: "Kannan@123", mobile: "8752360051", experience: 11, salary: 1050, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Inverter Setup"] },
    { name: "Logesh", email: "logesh52@gmail.com", password: "Logesh@123", mobile: "8752360052", experience: 7, salary: 850, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Madhan", email: "madhan53@gmail.com", password: "Madhan@123", mobile: "8752360053", experience: 12, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Door Installation"] },
    { name: "Nataraj", email: "nataraj54@gmail.com", password: "Nataraj@123", mobile: "8752360054", experience: 8, salary: 880, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Omprakash", email: "omprakash55@gmail.com", password: "Omprakash@123", mobile: "8752360055", experience: 14, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Pradeep", email: "pradeep56@gmail.com", password: "Pradeep@123", mobile: "8752360056", experience: 6, salary: 900, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "Switch Board Repair"] },
    { name: "Raghu", email: "raghu57@gmail.com", password: "Raghu@123", mobile: "8752360057", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Gate Welding"] },
    { name: "Sankar", email: "sankar58@gmail.com", password: "Sankar@123", mobile: "8752360058", experience: 9, salary: 1080, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Thiru", email: "thiru59@gmail.com", password: "Thiru@123", mobile: "8752360059", experience: 10, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Uday", email: "uday60@gmail.com", password: "Uday@123", mobile: "8752360060", experience: 6, salary: 820, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Vimal", email: "vimal61@gmail.com", password: "Vimal@123", mobile: "8752360061", experience: 9, salary: 1000, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Inverter Setup"] },
    { name: "Yogesh", email: "yogesh62@gmail.com", password: "Yogesh@123", mobile: "8752360062", experience: 7, salary: 850, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Ashok", email: "ashok63@gmail.com", password: "Ashok@123", mobile: "8752360063", experience: 11, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Balaji", email: "balaji64@gmail.com", password: "Balaji@123", mobile: "8752360064", experience: 8, salary: 900, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Charles", email: "charles65@gmail.com", password: "Charles@123", mobile: "8752360065", experience: 14, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "David", email: "david66@gmail.com", password: "David@123", mobile: "8752360066", experience: 6, salary: 900, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "Switch Board Repair"] },
    { name: "Ezhil", email: "ezhil67@gmail.com", password: "Ezhil@123", mobile: "8752360067", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Farooq", email: "farooq68@gmail.com", password: "Farooq@123", mobile: "8752360068", experience: 9, salary: 1050, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Gowtham", email: "gowtham69@gmail.com", password: "Gowtham@123", mobile: "8752360069", experience: 10, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Hemanth", email: "hemanth70@gmail.com", password: "Hemanth@123", mobile: "8752360070", experience: 6, salary: 820, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Imran", email: "imran71@gmail.com", password: "Imran@123", mobile: "8752360071", experience: 7, salary: 950, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Fan Installation"] },
    { name: "Jeeva", email: "jeeva72@gmail.com", password: "Jeeva@123", mobile: "8752360072", experience: 12, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Door Installation"] },
    { name: "Kishore", email: "kishore73@gmail.com", password: "Kishore@123", mobile: "8752360073", experience: 9, salary: 920, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Texture Painting"] },
    { name: "Lokesh", email: "lokesh74@gmail.com", password: "Lokesh@123", mobile: "8752360074", experience: 13, salary: 1250, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Mohan", email: "mohan75@gmail.com", password: "Mohan@123", mobile: "8752360075", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Gate Welding"] },
    { name: "Naveed", email: "naveed76@gmail.com", password: "Naveed@123", mobile: "8752360076", experience: 8, salary: 1040, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Prakash", email: "prakash77@gmail.com", password: "Prakash@123", mobile: "8752360077", experience: 9, salary: 980, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Rahul", email: "rahul78@gmail.com", password: "Rahul@123", mobile: "8752360078", experience: 6, salary: 800, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Sanjay", email: "sanjay79@gmail.com", password: "Sanjay@123", mobile: "8752360079", experience: 7, salary: 960, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "House Wiring"] },
    { name: "Tarun", email: "tarun80@gmail.com", password: "Tarun@123", mobile: "8752360080", experience: 10, salary: 1150, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Umesh", email: "umesh81@gmail.com", password: "Umesh@123", mobile: "8752360081", experience: 8, salary: 980, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Fan Installation"] },
    { name: "Varun", email: "varun82@gmail.com", password: "Varun@123", mobile: "8752360082", experience: 7, salary: 860, location: "Dharmapuri", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Leak Repair"] },
    { name: "Wasim", email: "wasim83@gmail.com", password: "Wasim@123", mobile: "8752360083", experience: 11, salary: 1180, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Xavier", email: "xavier84@gmail.com", password: "Xavier@123", mobile: "8752360084", experience: 9, salary: 900, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Texture Painting"] },
    { name: "Yash", email: "yash85@gmail.com", password: "Yash@123", mobile: "8752360085", experience: 13, salary: 1250, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Zubair", email: "zubair86@gmail.com", password: "Zubair@123", mobile: "8752360086", experience: 6, salary: 900, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "Switch Board Repair"] },
    { name: "Anand", email: "anand87@gmail.com", password: "Anand@123", mobile: "8752360087", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Steel Fabrication"] },
    { name: "Bharath", email: "bharath88@gmail.com", password: "Bharath@123", mobile: "8752360088", experience: 9, salary: 1080, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Chetan", email: "chetan89@gmail.com", password: "Chetan@123", mobile: "8752360089", experience: 10, salary: 1000, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Dharan", email: "dharan90@gmail.com", password: "Dharan@123", mobile: "8752360090", experience: 6, salary: 820, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Eshan", email: "eshan91@gmail.com", password: "Eshan@123", mobile: "8752360091", experience: 7, salary: 960, location: "Salem", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["House Wiring", "Fan Installation"] },
    { name: "Faizal", email: "faizal92@gmail.com", password: "Faizal@123", mobile: "8752360092", experience: 12, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Door Installation"] },
    { name: "Girish", email: "girish93@gmail.com", password: "Girish@123", mobile: "8752360093", experience: 9, salary: 910, location: "Namakkal", jobCategory: "Painter", skills: ["Painter"], subSkills: ["Wall Painting", "Exterior Painting"] },
    { name: "Harsha", email: "harsha94@gmail.com", password: "Harsha@123", mobile: "8752360094", experience: 14, salary: 1300, location: "Karur", jobCategory: "Mason", skills: ["Mason"], subSkills: ["Brick Work", "Concrete Work"] },
    { name: "Irfan", email: "irfan95@gmail.com", password: "Irfan@123", mobile: "8752360095", experience: 10, salary: 1100, location: "Salem", jobCategory: "Welder", skills: ["Welder"], subSkills: ["Arc Welding", "Gate Welding"] },
    { name: "Jithin", email: "jithin96@gmail.com", password: "Jithin@123", mobile: "8752360096", experience: 8, salary: 1040, location: "Tiruppur", jobCategory: "AC Technician", skills: ["AC Technician"], subSkills: ["AC Installation", "Gas Filling"] },
    { name: "Karthi", email: "karthi97@gmail.com", password: "Karthi@123", mobile: "8752360097", experience: 9, salary: 980, location: "Namakkal", jobCategory: "Tile Worker", skills: ["Tile Worker"], subSkills: ["Floor Tiling", "Wall Tiling"] },
    { name: "Lalit", email: "lalit98@gmail.com", password: "Lalit@123", mobile: "8752360098", experience: 6, salary: 800, location: "Karur", jobCategory: "Plumber", skills: ["Plumber"], subSkills: ["Pipe Fitting", "Bathroom Installation"] },
    { name: "Manav", email: "manav99@gmail.com", password: "Manav@123", mobile: "8752360099", experience: 7, salary: 970, location: "Krishnagiri", jobCategory: "Electrician", skills: ["Electrician"], subSkills: ["Fan Installation", "House Wiring"] },
    { name: "Nitin", email: "nitin100@gmail.com", password: "Nitin@123", mobile: "8752360100", experience: 10, salary: 1150, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Arun", email: "arun101@gmail.com", password: "Arun@123", mobile: "8752360101", experience: 8, salary: 1100, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Karthik", email: "karthik102@gmail.com", password: "Karthik@123", mobile: "8752360102", experience: 7, salary: 1050, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Vignesh", email: "vignesh103@gmail.com", password: "Vignesh@123", mobile: "8752360103", experience: 9, salary: 1150, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Cutting"] },
    { name: "Praveen", email: "praveen104@gmail.com", password: "Praveen@123", mobile: "8752360104", experience: 6, salary: 950, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Repair"] },
    { name: "Suresh", email: "suresh105@gmail.com", password: "Suresh@123", mobile: "8752360105", experience: 11, salary: 1200, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Ramesh", email: "ramesh106@gmail.com", password: "Ramesh@123", mobile: "8752360106", experience: 10, salary: 1150, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Polishing", "Furniture Repair"] },
    { name: "Manoj", email: "manoj107@gmail.com", password: "Manoj@123", mobile: "8752360107", experience: 5, salary: 900, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Cutting", "Furniture Assembly"] },
    { name: "Deepak", email: "deepak108@gmail.com", password: "Deepak@123", mobile: "8752360108", experience: 8, salary: 1080, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Santhosh", email: "santhosh109@gmail.com", password: "Santhosh@123", mobile: "8752360109", experience: 7, salary: 1020, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Polishing"] },
    { name: "Harish", email: "harish110@gmail.com", password: "Harish@123", mobile: "8752360110", experience: 6, salary: 980, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Repair", "Furniture Assembly"] },
    { name: "Ajay", email: "ajay111@gmail.com", password: "Ajay@123", mobile: "8752360111", experience: 9, salary: 1120, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Ravi", email: "ravi112@gmail.com", password: "Ravi@123", mobile: "8752360112", experience: 10, salary: 1150, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Design", "Wood Repair"] },
    { name: "Dinesh", email: "dinesh113@gmail.com", password: "Dinesh@123", mobile: "8752360113", experience: 7, salary: 1000, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Gokul", email: "gokul114@gmail.com", password: "Gokul@123", mobile: "8752360114", experience: 6, salary: 980, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Sathish", email: "sathish115@gmail.com", password: "Sathish@123", mobile: "8752360115", experience: 8, salary: 1080, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Polishing"] },
    { name: "Vinod", email: "vinod116@gmail.com", password: "Vinod@123", mobile: "8752360116", experience: 11, salary: 1200, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Bala", email: "bala117@gmail.com", password: "Bala@123", mobile: "8752360117", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Murugan", email: "murugan118@gmail.com", password: "Murugan@123", mobile: "8752360118", experience: 9, salary: 1100, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Kumar", email: "kumar119@gmail.com", password: "Kumar@123", mobile: "8752360119", experience: 7, salary: 1020, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Rajesh", email: "rajesh120@gmail.com", password: "Rajesh@123", mobile: "8752360120", experience: 10, salary: 1180, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Design", "Furniture Making"] },
    { name: "Senthil", email: "senthil121@gmail.com", password: "Senthil@123", mobile: "8752360121", experience: 8, salary: 1100, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Prakash", email: "prakash122@gmail.com", password: "Prakash@123", mobile: "8752360122", experience: 9, salary: 1120, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Hari", email: "hari123@gmail.com", password: "Hari@123", mobile: "8752360123", experience: 6, salary: 980, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Raghu", email: "raghu124@gmail.com", password: "Raghu@123", mobile: "8752360124", experience: 7, salary: 1020, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Kannan", email: "kannan125@gmail.com", password: "Kannan@123", mobile: "8752360125", experience: 11, salary: 1200, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Saravanan", email: "saravanan126@gmail.com", password: "Saravanan@123", mobile: "8752360126", experience: 10, salary: 1180, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Design", "Furniture Repair"] },
    { name: "Mohan", email: "mohan127@gmail.com", password: "Mohan@123", mobile: "8752360127", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Cutting", "Furniture Assembly"] },
    { name: "Anand", email: "anand128@gmail.com", password: "Anand@123", mobile: "8752360128", experience: 8, salary: 1080, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Siva", email: "siva129@gmail.com", password: "Siva@123", mobile: "8752360129", experience: 7, salary: 1000, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Polishing"] },
    { name: "Jagan", email: "jagan130@gmail.com", password: "Jagan@123", mobile: "8752360130", experience: 9, salary: 1130, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Balaji", email: "balaji131@gmail.com", password: "Balaji@123", mobile: "8752360131", experience: 8, salary: 1100, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Karthikeyan", email: "karthikeyan132@gmail.com", password: "Karthikeyan@123", mobile: "8752360132", experience: 9, salary: 1120, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Sundar", email: "sundar133@gmail.com", password: "Sundar@123", mobile: "8752360133", experience: 6, salary: 980, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Rajan", email: "rajan134@gmail.com", password: "Rajan@123", mobile: "8752360134", experience: 7, salary: 1020, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Venkatesh", email: "venkatesh135@gmail.com", password: "Venkatesh@123", mobile: "8752360135", experience: 11, salary: 1200, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Manikandan", email: "manikandan136@gmail.com", password: "Manikandan@123", mobile: "8752360136", experience: 10, salary: 1180, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Design", "Furniture Repair"] },
    { name: "Thangaraj", email: "thangaraj137@gmail.com", password: "Thangaraj@123", mobile: "8752360137", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Cutting", "Furniture Assembly"] },
    { name: "Selvam", email: "selvam138@gmail.com", password: "Selvam@123", mobile: "8752360138", experience: 8, salary: 1080, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Repair"] },
    { name: "Perumal", email: "perumal139@gmail.com", password: "Perumal@123", mobile: "8752360139", experience: 7, salary: 1000, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Polishing"] },
    { name: "Subramani", email: "subramani140@gmail.com", password: "Subramani@123", mobile: "8752360140", experience: 9, salary: 1130, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Raghavan", email: "raghavan141@gmail.com", password: "Raghavan@123", mobile: "8752360141", experience: 8, salary: 1090, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Chandran", email: "chandran142@gmail.com", password: "Chandran@123", mobile: "8752360142", experience: 6, salary: 970, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Repair", "Furniture Assembly"] },
    { name: "Loganathan", email: "loganathan143@gmail.com", password: "Loganathan@123", mobile: "8752360143", experience: 7, salary: 1010, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Cutting"] },
    { name: "Palanisamy", email: "palanisamy144@gmail.com", password: "Palanisamy@123", mobile: "8752360144", experience: 10, salary: 1160, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Muthu", email: "muthu145@gmail.com", password: "Muthu@123", mobile: "8752360145", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Velmurugan", email: "velmurugan146@gmail.com", password: "Velmurugan@123", mobile: "8752360146", experience: 9, salary: 1140, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Arivazhagan", email: "arivazhagan147@gmail.com", password: "Arivazhagan@123", mobile: "8752360147", experience: 8, salary: 1070, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Repair", "Furniture Assembly"] },
    { name: "Kandasamy", email: "kandasamy148@gmail.com", password: "Kandasamy@123", mobile: "8752360148", experience: 11, salary: 1210, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Duraisamy", email: "duraisamy149@gmail.com", password: "Duraisamy@123", mobile: "8752360149", experience: 7, salary: 1030, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Sakthivel", email: "sakthivel150@gmail.com", password: "Sakthivel@123", mobile: "8752360150", experience: 10, salary: 1170, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Design", "Furniture Repair"] },
    { name: "Ravichandran", email: "ravichandran151@gmail.com", password: "Ravi@123", mobile: "8752360151", experience: 9, salary: 1120, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Ganesan", email: "ganesan152@gmail.com", password: "Ganesan@123", mobile: "8752360152", experience: 8, salary: 1080, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Ilango", email: "ilango153@gmail.com", password: "Ilango@123", mobile: "8752360153", experience: 6, salary: 970, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Rathinam", email: "rathinam154@gmail.com", password: "Rathinam@123", mobile: "8752360154", experience: 10, salary: 1180, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Thiyagarajan", email: "thiyagarajan155@gmail.com", password: "Thiyagarajan@123", mobile: "8752360155", experience: 11, salary: 1210, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Marimuthu", email: "marimuthu156@gmail.com", password: "Marimuthu@123", mobile: "8752360156", experience: 7, salary: 1030, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Repair", "Wood Cutting"] },
    { name: "Ponnusamy", email: "ponnusamy157@gmail.com", password: "Ponnusamy@123", mobile: "8752360157", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Nagaraj", email: "nagaraj158@gmail.com", password: "Nagaraj@123", mobile: "8752360158", experience: 9, salary: 1140, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Boopathy", email: "boopathy159@gmail.com", password: "Boopathy@123", mobile: "8752360159", experience: 8, salary: 1090, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Rajendran", email: "rajendran160@gmail.com", password: "Rajendran@123", mobile: "8752360160", experience: 10, salary: 1160, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Kaliyaperumal", email: "kaliyaperumal161@gmail.com", password: "Kaliyaperumal@123", mobile: "8752360161", experience: 9, salary: 1120, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Arumugam", email: "arumugam162@gmail.com", password: "Arumugam@123", mobile: "8752360162", experience: 8, salary: 1080, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Chinnasamy", email: "chinnasamy163@gmail.com", password: "Chinnasamy@123", mobile: "8752360163", experience: 6, salary: 970, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Palaniappan", email: "palaniappan164@gmail.com", password: "Palaniappan@123", mobile: "8752360164", experience: 10, salary: 1180, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Ramasamy", email: "ramasamy165@gmail.com", password: "Ramasamy@123", mobile: "8752360165", experience: 11, salary: 1210, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Shanmugam", email: "shanmugam166@gmail.com", password: "Shanmugam@123", mobile: "8752360166", experience: 7, salary: 1030, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Repair", "Wood Cutting"] },
    { name: "Natesan", email: "natesan167@gmail.com", password: "Natesan@123", mobile: "8752360167", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Muthusamy", email: "muthusamy168@gmail.com", password: "Muthusamy@123", mobile: "8752360168", experience: 9, salary: 1140, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Palanivel", email: "palanivel169@gmail.com", password: "Palanivel@123", mobile: "8752360169", experience: 8, salary: 1090, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Veerappan", email: "veerappan170@gmail.com", password: "Veerappan@123", mobile: "8752360170", experience: 10, salary: 1160, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Paramasivan", email: "paramasivan171@gmail.com", password: "Paramasivan@123", mobile: "8752360171", experience: 8, salary: 1080, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Rathinasamy", email: "rathinasamy172@gmail.com", password: "Rathinasamy@123", mobile: "8752360172", experience: 9, salary: 1120, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Sivakumar", email: "sivakumar173@gmail.com", password: "Sivakumar@123", mobile: "8752360173", experience: 6, salary: 970, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Dhanapal", email: "dhanapal174@gmail.com", password: "Dhanapal@123", mobile: "8752360174", experience: 10, salary: 1180, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Chandrasekar", email: "chandrasekar175@gmail.com", password: "Chandrasekar@123", mobile: "8752360175", experience: 11, salary: 1200, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Rajamani", email: "rajamani176@gmail.com", password: "Rajamani@123", mobile: "8752360176", experience: 7, salary: 1020, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Repair", "Wood Cutting"] },
    { name: "Murugesan", email: "murugesan177@gmail.com", password: "Murugesan@123", mobile: "8752360177", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Anbalagan", email: "anbalagan178@gmail.com", password: "Anbalagan@123", mobile: "8752360178", experience: 9, salary: 1140, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Singaravel", email: "singaravel179@gmail.com", password: "Singaravel@123", mobile: "8752360179", experience: 8, salary: 1090, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Kuppusamy", email: "kuppusamy180@gmail.com", password: "Kuppusamy@123", mobile: "8752360180", experience: 10, salary: 1160, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Marappan", email: "marappan181@gmail.com", password: "Marappan@123", mobile: "8752360181", experience: 7, salary: 1020, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Ravikumar", email: "ravikumar182@gmail.com", password: "Ravikumar@123", mobile: "8752360182", experience: 8, salary: 1080, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Wood Repair"] },
    { name: "Sathyan", email: "sathyan183@gmail.com", password: "Sathyan@123", mobile: "8752360183", experience: 6, salary: 970, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Thangavel", email: "thangavel184@gmail.com", password: "Thangavel@123", mobile: "8752360184", experience: 10, salary: 1180, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Manoharan", email: "manoharan185@gmail.com", password: "Manoharan@123", mobile: "8752360185", experience: 11, salary: 1200, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Sridhar", email: "sridhar186@gmail.com", password: "Sridhar@123", mobile: "8752360186", experience: 7, salary: 1010, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Repair", "Wood Cutting"] },
    { name: "Rengaraj", email: "rengaraj187@gmail.com", password: "Rengaraj@123", mobile: "8752360187", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Selvaraj", email: "selvaraj188@gmail.com", password: "Selvaraj@123", mobile: "8752360188", experience: 9, salary: 1140, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Pandian", email: "pandian189@gmail.com", password: "Pandian@123", mobile: "8752360189", experience: 8, salary: 1090, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Arjunan", email: "arjunan190@gmail.com", password: "Arjunan@123", mobile: "8752360190", experience: 10, salary: 1160, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Karuppasamy", email: "karuppasamy191@gmail.com", password: "Karuppasamy@123", mobile: "8752360191", experience: 8, salary: 1100, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Madasamy", email: "madasamy192@gmail.com", password: "Madasamy@123", mobile: "8752360192", experience: 7, salary: 1000, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Wood Repair", "Furniture Assembly"] },
    { name: "Ayyappan", email: "ayyappan193@gmail.com", password: "Ayyappan@123", mobile: "8752360193", experience: 6, salary: 960, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Cutting"] },
    { name: "Rajadurai", email: "rajadurai194@gmail.com", password: "Rajadurai@123", mobile: "8752360194", experience: 9, salary: 1130, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] },
    { name: "Devaraj", email: "devaraj195@gmail.com", password: "Devaraj@123", mobile: "8752360195", experience: 10, salary: 1180, location: "Namakkal", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Cabinet Design"] },
    { name: "Kumaravel", email: "kumaravel196@gmail.com", password: "Kumaravel@123", mobile: "8752360196", experience: 7, salary: 1020, location: "Coimbatore", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Repair", "Wood Cutting"] },
    { name: "Rathinavel", email: "rathinavel197@gmail.com", password: "Rathinavel@123", mobile: "8752360197", experience: 5, salary: 900, location: "Erode", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Assembly", "Wood Cutting"] },
    { name: "Muthukumar", email: "muthukumar198@gmail.com", password: "Muthukumar@123", mobile: "8752360198", experience: 8, salary: 1090, location: "Salem", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Furniture Making", "Wood Polishing"] },
    { name: "Nallathambi", email: "nallathambi199@gmail.com", password: "Nallathambi@123", mobile: "8752360199", experience: 9, salary: 1140, location: "Tiruppur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Door Installation", "Wood Repair"] },
    { name: "Kalimuthu", email: "kalimuthu200@gmail.com", password: "Kalimuthu@123", mobile: "8752360200", experience: 10, salary: 1170, location: "Karur", jobCategory: "Carpenter", skills: ["Carpenter"], subSkills: ["Cabinet Making", "Furniture Repair"] }
];

const seedWorkers = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log("MongoDB connected.\n");

        let created = 0;
        let skipped = 0;

        for (const w of workers) {
            // Check if user already exists
            const existing = await User.findOne({ email: w.email.toLowerCase() });
            if (existing) {
                console.log(`  ⏭  SKIP: ${w.name} (${w.email}) — already exists`);
                skipped++;
                continue;
            }

            // 1. Create User account
            const hashedPassword = await bcrypt.hash(w.password, 10);
            const user = new User({
                name: w.name,
                email: w.email.toLowerCase(),
                password: hashedPassword,
                role: "worker"
            });
            await user.save();

            // 2. Create Worker Profile
            const profile = new WorkerProfile({
                userId: user._id,
                mobile: w.mobile,
                jobCategory: w.jobCategory,
                experience: w.experience,
                location: w.location,
                salary: w.salary,
                skills: w.skills,
                subSkills: w.subSkills,
                languages: ["Tamil", "English"],
                availability: true,
                averageRating: 0,
                totalReviews: 0,
                isVerified: true
            });
            await profile.save();

            console.log(`  ✅ ADDED: ${w.name} — ${w.jobCategory} (${w.location}) — ₹${w.salary}/day`);
            created++;
        }

        console.log(`\n========================================`);
        console.log(`  Total Workers Added:   ${created}`);
        console.log(`  Already Existed:       ${skipped}`);
        console.log(`  Total in Script:       ${workers.length}`);
        console.log(`========================================\n`);

        process.exit(0);
    } catch (err) {
        console.error("Error seeding workers:", err.message);
        process.exit(1);
    }
};

seedWorkers();
